api_version = "2026-01"

[[extensions]]
uid = "5d4fd9c8-9ffe-27f5-b3a1-c7f81186bbf83c90721a"
type = "ui_extension"
name = "出庫 / 在庫処理"
handle = "stock-transfer-tile"
description = "出庫 / 在庫処理"

[[extensions.targeting]]
target = "pos.home.tile.render"
module = "./src/Tile.jsx"

[[extensions.targeting]]
target = "pos.home.modal.render"
module = "./src/ModalOutbound.jsx"
